name: Generate Snake Game

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Game from contribution graph
        uses: Platane/snk@v2
        with:
          github_user_name: rzeta-10  # Replace with your GitHub username
          outputs: dist/snake.svg  # Fix: 'outputs' instead of 'output'

      - name: Commit the Snake Game
        run: |
          git config --local user.name "rzeta-10"
          git config --local user.email "cs22b1093@iiitdm.ac.in"
          git add dist/snake.svg
          git commit -m "Generate snake animation"
          git push

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
